// apps/host/src/routes/quizzes/page.tsx
import { instance } from '../../mf-runtime';

const QuizzesPage = instance!.createLazyComponent({
  loader: () => import('quizzes/Page'),
  loading: <div style={{ padding: 24, color: '#64748b' }}>Loading remote…</div>,
  export: 'default',
  fallback: () => <div style={{ padding: 24, color: '#dc2626' }}>Failed to load quizzes MFE</div>,
});

export default function QuizzesRoute() {
  return <QuizzesPage greeting="Greetings from the host —" />;
}

// src/routes/quizzes/+page.svelte
<script lang="ts">
	import SvelteMFE from '$lib/mfe-adapters/SvelteMFE.svelte';
	import type { QuizzesProps } from 'quizzes/App';

	const loadQuizzes = () => import('quizzes/App');

	const props: QuizzesProps = { greeting: 'Greetings from the host —' };
</script>

<SvelteMFE load={loadQuizzes} {props}>
	{#snippet fallback()}
		<div class="loading">Loading quizzes…</div>
	{/snippet}
</SvelteMFE>

<style>
	.loading {
		padding: 24px;
		color: #64748b;
	}
</style>
