// src/routes/students/+page.svelte
<script lang="ts">
	import SvelteMFE from '$lib/mfe-adapters/SvelteMFE.svelte';
	import type { StudentsProps } from 'students/App';

	const loadStudents = () => import('students/App');

	const props: StudentsProps = {};
</script>

<SvelteMFE load={loadStudents} {props}>
	{#snippet fallback()}
		<div class="loading">Loading students…</div>
	{/snippet}
</SvelteMFE>

<style>
	.loading {
		padding: 24px;
		color: #64748b;
	}
</style>

// apps/host/src/routes/students/page.tsx
import { instance } from '../../mf-runtime';

const StudentsPage = instance!.createLazyComponent({
  loader: () => import('students/Page'),
  loading: <div style={{ padding: 24, color: '#64748b' }}>Loading remote…</div>,
  export: 'default',
  fallback: () => <div style={{ padding: 24, color: '#dc2626' }}>Failed to load students MFE</div>,
});

export default function StudentsRoute() {
  return <StudentsPage initialCount={5} />;
}
