// apps/host/pages/students/+Page.svelte
<script lang="ts">
  import Federated from '../../src/Federated.svelte';
  const loadStudents = () => import('students/Page');
</script>

<Federated load={loadStudents} props={{ initialCount: 5 }}>
  {#snippet fallback()}
    <div class="loading">Loading remote…</div>
  {/snippet}
</Federated>

<style>
  .loading { padding: 24px; color: #64748b; }
</style>

// apps/host/src/routes/students/page.tsx
import { lazy, Suspense } from 'react';

const StudentsPage = lazy(() => import('students/Page'));

export default function StudentsRoute() {
  return (
    <Suspense fallback={<div style={{ padding: 24, color: '#64748b' }}>Loading remote…</div>}>
      <StudentsPage initialCount={5} />
    </Suspense>
  );
}
