// apps/host/src/routes/quizzes/page.tsx
import { lazy, Suspense } from 'react';

const QuizzesPage = lazy(() => import('quizzes/Page'));

export default function QuizzesRoute() {
  return (
    <Suspense fallback={<div style={{ padding: 24, color: '#64748b' }}>Loading remote…</div>}>
      <QuizzesPage greeting="Greetings from the host —" />
    </Suspense>
  );
}

// apps/host/pages/quizzes/+Page.svelte
<script lang="ts">
  import Federated from '../../src/Federated.svelte';
  const loadQuizzes = () => import('quizzes/Page');
</script>

<Federated load={loadQuizzes} props={{ greeting: 'Greetings from the host —' }}>
  {#snippet fallback()}
    <div class="loading">Loading remote…</div>
  {/snippet}
</Federated>

<style>
  .loading { padding: 24px; color: #64748b; }
</style>
