// src/routes/settings/+page.svelte
<script lang="ts">
	import ReactMFE from '$lib/mfe-adapters/ReactMFE.svelte';
	import type { SettingsData, SettingsProps } from 'settings/App';

	const loadSettings = () => import('settings/App');

	const props: SettingsProps = {
		userName: 'Kamran',
		userEmail: 'kamran@juicemind.app',
		onSave: (data: SettingsData) =>
			alert('Host received settings save:\n' + JSON.stringify(data, null, 2))
	};
</script>

<ReactMFE load={loadSettings} {props}>
	{#snippet fallback()}
		<div class="loading">Loading settings…</div>
	{/snippet}
</ReactMFE>

<style>
	.loading {
		padding: 24px;
		color: #64748b;
	}
</style>

// apps/host/src/routes/settings/page.tsx
import type { SettingsData } from 'settings/App';
import SvelteIsland from '../../SvelteIsland';

const loadSettings = () => import('settings/App');

export default function SettingsRoute() {
  return (
    <SvelteIsland
      load={loadSettings}
      props={{
        userName: 'Kamran',
        userEmail: 'kamran@juicemind.app',
        onSave: (data: SettingsData) => {
          alert(`Host received settings save:\n${JSON.stringify(data, null, 2)}`);
        },
      }}
    />
  );
}
